### ISSUE TITLE
host name validation failed when setting host in  location conf.

### ISSUE THREAD

**Issue by WENPIN1** [vicanso/pingap#10]
After setting host in location conf

[locations.lo]
upstream = "charts"
path = "/"
host = "localhost"
proxy_set_headers = ["name:value"]
proxy_add_headers = ["name:value"]
rewrite = ""
plugins = ["pingap:requestId", "pingap:stats"],

The result pf `curl -v "http://localhost:6188"` is incorrect.
It seems [header.uri.host() ](https://github.com/vicanso/pingap/blob/596a20c2717e3e5b1f6cb91d0245a378ca2bf679/src/proxy/server.rs#L453) didn't work as expected.

`````
*   Trying [::1]:6188...
* connect to ::1 port 6188 failed: Connection refused
*   Trying 127.0.0.1:6188...
* Connected to localhost (127.0.0.1) port 6188
> GET / HTTP/1.1
> Host: localhost:6188

> User-Agent: curl/8.4.0
> Accept: */*
> 
< HTTP/1.1 500 Internal Server Error
< Content-Length: 32
< Cache-Control: private, no-store
< Date: Fri, 24 May 2024 10:05:54 GMT
< Connection: keep-alive
< 
* Connection #0 to host localhost left intact
Location not found, host: path:/
%      
`````````           
<img width="893" alt="截圖 2024-05-24 18 06 16" src="https://github.com/vicanso/pingap/assets/13994729/87925362-1535-4e8e-a4dc-238c18bd39b2">

**Comment by vicanso** [comment]
@WENPIN1  Please try the latest version. And the host should be `localhost:6188`.

> Host: localhost:6188

**Comment by WENPIN1** [comment]
Why not split the host:port into host string for the convenience ?
https://github.com/vicanso/pingap/blob/main/src/util/mod.rs#L208)
        return Some(host.to_str().unwrap_or_default().split(':').next().map(|s|s.to_string());   // the string before ':'


Sorry for your inconvenience !

-WENPIN

**Comment by WENPIN1** [comment]
Also, please swap the variables for category:{}, step:{} on correct positions.

Thank you very much!
-WENPIN

https://github.com/vicanso/pingap/blob/06f5c4d8b69697f790b5f594d98188596ac3a168/src/main.rs#L370
https://github.com/vicanso/pingap/blob/06f5c4d8b69697f790b5f594d98188596ac3a168/src/main.rs#L371
https://github.com/vicanso/pingap/blob/06f5c4d8b69697f790b5f594d98188596ac3a168/src/main.rs#L372




https://github.com/vicanso/pingap/blob/06f5c4d8b69697f790b5f594d98188596ac3a168/src/main.rs#L377
https://github.com/vicanso/pingap/blob/06f5c4d8b69697f790b5f594d98188596ac3a168/src/main.rs#L378
https://github.com/vicanso/pingap/blob/06f5c4d8b69697f790b5f594d98188596ac3a168/src/main.rs#L379

**Comment by vicanso** [comment]
I made a mistake about http host and host. I will look up how other reverse proxies handle it and decide how to adjust it.
