### ISSUE TITLE
How to config reverse proxy for domain?

### ISSUE THREAD

**Issue by adammakowskidev** [vicanso/pingap#11]
Hi @vicanso 
I am just testing Pingap
I am wondering how I can create a proxy for a domain and use cache? Can you provide some example? The documentation is small
In nginx I do it this way
```
proxy_cache_path /var/local/cache/domain_net keys_zone=domain_net:10m inactive=1y;


server {
    listen 443 quic reuseport;
    listen [::]:443 quic reuseport;
    listen 443 ssl;
    listen [::]:443 ssl;
    listen 80;
    http2 on;
    http3 on;
    server_name cdn.domain.com;

    # SSL location
    ssl_certificate /var/local/certificate.pem;
    ssl_certificate_key /var/local/private.key;
 
    # SSL settings
    ssl_protocols TLSv1.3 TLSv1.2;
    ssl_early_data on;
    ssl_session_tickets on;
    
    # http3/quic settings
    http3_stream_buffer_size 1m;

    # global website headers
    add_header Alt-Svc 'h3=":443"; ma=86400';
    add_header Cache-Status $upstream_cache_status;

    # proxy CDN cache settings
    location / {
        proxy_set_header Early-Data $ssl_early_data;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Access-Control-Allow-Origin *;
        proxy_set_header "Connection" "";
        proxy_cache domain_net;
        proxy_cache_valid any 1d;
        proxy_pass https://domain.net;
    }
}
```

**Comment by adammakowskidev** [comment]
@vicanso
Thank you for your response.  I need some time to do some tests.  Can the cache currently be configured in any way?  Example TTL?

**Comment by adammakowskidev** [comment]
@vicanso 
Just testing, everything works fine! I just made it so that Caddy provides SSL, pingap handle proxy website + cache and Caddy serve SSL.

Currently, I don't know if there is an option to automatically receive SSL in Pingap?

**Comment by vicanso** [comment]
> @vicanso Thank you for your response. I need some time to do some tests. Can the cache currently be configured in any way? Example TTL?

Cache ttl is parse from http response header `cache-control`

**Comment by adammakowskidev** [comment]
So I have to overwrite this header?  Many websites have their static files length set to one year.  This is a bit long for the cache.  Maybe it would be useful to set the cache age separately?

**Comment by vicanso** [comment]
`Cache-Control: public, max-age=xxx, s-maxage=xxx`, the s-maxage will be used as ttl. I'll find a way to set the maximum TTL later.


On Jun 6, 2024, at 10:18 PM, Adam Makowski ***@***.***> wrote:



So I have to overwrite this header? Many websites have their static files length set to one year. This is a bit long for the cache. Maybe it would be useful to set the cache age separately?

**Comment by vicanso** [comment]
@adammakowskidev  Now you can set cache max ttl:

```toml
[plugins.commonCache]
category = "cache"
eviction = true
lock = "1s"
max_file_size = "1MB"
max_ttl = "5m"
predictor = true
```
If ttl get from `cache-control` > 5 minutes, ttl will be set 5 minutes.
