### ISSUE TITLE
Many SSL errors

### ISSUE THREAD

**Issue by adammakowskidev** [vicanso/pingap#14]
Hi
@vicanso We have already talked about this but I would like to put the information somewhere in one place, in order to find the problem more easily. I am currently using version 0.5.15 of Pingap. The logs show me many errors for SSL.

> ERROR 2024-06-14T17:17:10.327780367+00:00 Downstream handshake error  TLSHandshakeFailure context: TLS accept() failed: unexpected EOF
> ERROR 2024-06-14T17:17:37.588841557+00:00 Downstream handshake error  TLSHandshakeFailure context: TLS accept() failed: error:0A000412:SSL routines:ssl3_read_bytes:ssl/tls alert bad certificate:ssl/record/rec_layer_s3.c:865:SSL alert number 42
> ERROR 2024-06-14T17:17:37.589088519+00:00 Downstream handshake error  TLSHandshakeFailure context: TLS accept() failed: error:0A000412:SSL routines:ssl3_read_bytes:ssl/tls alert bad certificate:ssl/record/rec_layer_s3.c:865:SSL alert number 42
> ERROR 2024-06-14T17:17:37.589185560+00:00 Downstream handshake error  TLSHandshakeFailure context: TLS accept() failed: error:0A000412:SSL routines:ssl3_read_bytes:ssl/tls alert bad certificate:ssl/record/rec_layer_s3.c:865:SSL alert number 42
> ERROR 2024-06-14T17:17:37.590562892+00:00 Downstream handshake error  TLSHandshakeFailure context: TLS accept() failed: error:0A000412:SSL routines:ssl3_read_bytes:ssl/tls alert bad certificate:ssl/record/rec_layer_s3.c:865:SSL alert number 42
> ERROR 2024-06-14T17:18:08.741060757+00:00 Downstream handshake error  TLSHandshakeFailure context: TLS accept() failed: unexpected EOF
> ERROR 2024-06-14T17:18:08.800909100+00:00 Downstream handshake error  TLSHandshakeFailure context: TLS accept() failed: unexpected EOF
> ERROR 2024-06-14T17:20:13.838447538+00:00 Downstream handshake error  TLSHandshakeFailure context: TLS accept() failed: error:0A000418:SSL routines:ssl3_read_bytes:tlsv1 alert unknown ca:ssl/record/rec_layer_s3.c:865:SSL alert number 48
> ERROR 2024-06-14T17:20:57.623196668+00:00 H2 handshake error  HandshakeError context: while h2 handshaking with client cause: connection closed before reading preface
> ERROR 2024-06-14T17:28:38.877291092+00:00 Downstream handshake error  TLSHandshakeFailure context: TLS accept() failed: error:0A0000C1:SSL routines:tls_post_process_client_hello:no shared cipher:ssl/statem/statem_srvr.c:2326:
> ERROR 2024-06-14T17:28:39.282975094+00:00 Downstream handshake error  TLSHandshakeFailure context: TLS accept() failed: unexpected EOF
> ERROR 2024-06-14T17:28:39.392801104+00:00 Downstream handshake error  TLSHandshakeFailure context: TLS accept() failed: error:0A000102:SSL routines:tls_early_post_process_client_hello:unsupported protocol:ssl/statem/statem_srvr.c:1755:
> ERROR 2024-06-14T17:28:39.760675602+00:00 Downstream handshake error  TLSHandshakeFailure context: TLS accept() failed: unexpected EOF
> ERROR 2024-06-14T17:28:40.005621412+00:00 Downstream handshake error  TLSHandshakeFailure context: TLS accept() failed: unexpected EOF
> ERROR 2024-06-14T18:58:04.285808895+00:00 H2 handshake error  HandshakeError context: while h2 handshaking with client cause: connection closed before reading preface
> ERROR 2024-06-14T18:58:04.285835255+00:00 H2 handshake error  HandshakeError context: while h2 handshaking with client cause: connection closed before reading preface
> ERROR 2024-06-14T18:58:04.286127817+00:00 H2 handshake error  HandshakeError context: while h2 handshaking with client cause: connection closed before reading preface
> ERROR 2024-06-14T18:58:04.286275538+00:00 H2 handshake error  HandshakeError context: while h2 handshaking with client cause: connection closed before reading preface
> ERROR 2024-06-14T18:58:04.286427819+00:00 H2 handshake error  HandshakeError context: while h2 handshaking with client cause: connection closed before reading preface
> ERROR 2024-06-14T19:01:11.993158263+00:00 Downstream handshake error  TLSHandshakeFailure context: TLS accept() failed: error:0A000418:SSL routines:ssl3_read_bytes:tlsv1 alert unknown ca:ssl/record/rec_layer_s3.c:865:SSL alert number 48
> ERROR 2024-06-14T19:01:19.316955826+00:00 Downstream handshake error  TLSHandshakeFailure context: TLS accept() failed: unexpected EOF
> ERROR 2024-06-14T19:02:37.591869+00:00 H2 handshake error  HandshakeError context: while h2 handshaking with client cause: connection closed before reading preface
> ERROR 2024-06-14T19:07:56.549146842+00:00 Downstream handshake error  TLSHandshakeFailure context: TLS accept() failed: error:0A000418:SSL routines:ssl3_read_bytes:tlsv1 alert unknown ca:ssl/record/rec_layer_s3.c:865:SSL alert number 48
> ERROR 2024-06-14T19:07:57.403035607+00:00 Downstream handshake error  TLSHandshakeFailure context: TLS accept() failed: unexpected EOF
>

**Comment by vicanso** [comment]
https://github.com/cloudflare/pingora/issues/278

**Comment by vicanso** [comment]
The latest version supports tlsv1.1 now.
