### ISSUE TITLE
使用docker compose启动异常

### ISSUE THREAD

**Issue by fun7257** [vicanso/pingap#22]
启动pingap，3018端口无法访问，容器会无限重启，log如下

error: the following required arguments were not provided:
  --conf <CONF>

Usage: pingap --conf <CONF>

For more information, try '--help'.

**Comment by vicanso** [comment]
麻烦提供完整的参数配置

**Comment by fun7257** [comment]
services:
  pingap:
    image: vicanso/pingap
    restart: always
    ports:
      - 80:80
      - 443:443
      - 3018:3018
    volumes:
      - ./conf:/opt/pingap/conf
    environment:
      PINGAP_CONF: /opt/pingap/conf
      PINGAP_ADMIN_ADDR: 0.0.0.0:3018
      PINGAP_ADMIN_USER: pingap
      PINGAP_ADMIN_PASSWORD: pingap
      PINGAP_AUTORELOAD: true
    entrypoint: |
      pingap

**Comment by fun7257** [comment]
Linux pi5 6.6.31+rpt-rpi-2712 #1 SMP PREEMPT Debian 1:6.6.31-1+rpt1 (2024-05-29) aarch64 GNU/Linux

**Comment by vicanso** [comment]
使用pingap的版本中否 >= 0.7.0？

**Comment by fun7257** [comment]
本地缓存了旧版本的镜像，使用docker compose up启动没有更新，重新拉取镜像即可启动
