### ISSUE TITLE
如何开启prometheus指标

### ISSUE THREAD

**Issue by charlesqing** [vicanso/pingap#32]
[servers.pingap]
addr = "0.0.0.0:6188"
locations = ["remote"]
#access_log = "combined"
threads = 1
tcp_fast_open = 10
prometheus_metrics = "/metrics"

按照上面的配置，metrics指标无法访问

**Comment by vicanso** [comment]
是否没重启？ 我尝试过配置如下可访问： https://charts.npmtrend.com/metrics

[servers.pingap]
access_log = '{remote} "{method} {uri} {proto}" {status} {size_human} "{referer}" "{user_agent}" "tls:{:tls_version}-{:tls_cipher}-{:tls_handshake_time}" "{:connection_time} {:connection_reused}"'
addr = "0.0.0.0:443"
global_certificates = true
locations = [
    "charts",
    "cybertect",
    "diving",
    "ip",
]
prometheus_metrics = "/metrics"
