### ISSUE TITLE
Using pingora to process grpc stream encounters WriteError

### ISSUE THREAD

**Issue by huahuadeliaoliao** [vicanso/pingap#37]
Have you ever encountered the following error when using pingora to process grpc flow:

`[2024-09-29T06:59:36Z ERROR pingora_proxy] Fail to proxy: Upstream WriteError context: Peer: addr: 127.0.0.1:4317, scheme: HTTP,sni: otel-col.example.com, cause:  context: while writing h2 request body cause: user error: inactive stream, status: 502, tries: 1, retry: false, POST https://otel-col.example.com/opentelemetry.proto.collector.metrics.v1.MetricsService/Export, Host: `

**Comment by huahuadeliaoliao** [comment]
This problem doesn't seem to occur when I use pingap to proxy grpc, so I want to know if pingap does anything to process the grpc stream.

**Comment by vicanso** [comment]
Try the latest commit of pingora, not v0.0.3.
