### ISSUE TITLE
添加windows支持

### ISSUE THREAD

**Issue by 0x9bb1** [vicanso/pingap#43]
上游`pingora`已支持windows编译，`pingap`能否添加windows支持

**Comment by vicanso** [comment]
后续版本尝试构建windows的版本

**Comment by vicanso** [comment]
尝试编译，还是存在较多问题，等官方正式支持后再调整。
https://github.com/vicanso/pingap/actions/runs/11345924028

**Comment by vicanso** [comment]
@0x9bb1 最新版本已支持windows，由于无windows机器，并未充分测试
