### ISSUE TITLE
多次更改service的监听地址，pingap不会在本地创建出对应的监听

### ISSUE THREAD

**Issue by qiuyuyin** [vicanso/pingap#49]
**多次修改，把server的监听从4000逐渐改成4005，4004和4005都没创建出来**
![image](https://github.com/user-attachments/assets/692d0b9b-c1b4-459f-902c-4f1bec753215)

**下面是显示的问题**
![image](https://github.com/user-attachments/assets/e24a6e3f-cd65-4ab5-a07b-03cd66b7872e)

【建议】
不让前端修改server的监听地址

**Comment by vicanso** [comment]
麻烦确认使用的是什么版本？只有linux（非docker)的版本才支持upgrade模式，启动时的参数需要指定`-a -u`
