### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by liudonghua123** [vicanso/pingap#5]
I find this project is build with cargo/rust, how about building windows binary too?

```
rustup update
rustup target add i686-pc-windows-msvc
rustup target add x86_64-pc-windows-msvc
cargo build --release --target=stable-i686-pc-windows-msvc
cargo build --release --target=stable-x86_64-pc-windows-msvc
```

See also the github action for macos.

https://github.com/vicanso/pingap/blob/d685f9f751b39dcedea7fcccd04c11656e82663c/.github/workflows/publish.yml#L12-L36

**Comment by fastkits** [comment]
Not supported by windows ！

**Comment by vicanso** [comment]
I'm sorry, but since Pingora only supports Unix-like systems, so Pingap is the same. https://github.com/cloudflare/pingora?tab=readme-ov-file#systems
