### ISSUE TITLE
[bug] 删除server，本地监听没有删除

### ISSUE THREAD

**Issue by qiuyuyin** [vicanso/pingap#50]
2024-10-30T14:29:20.982685184+08:00 DEBUG current config diff from new config updated_category_list="server" original_diff_result="--server:test\n"
2024-10-30T14:29:20.982765235+08:00 DEBUG current config diff from hot realod config updated_category_list="" original_diff_result=""

上面是日志已经触发，但是不会导致对应机器上的配置删除，是为了复用？
![image](https://github.com/user-attachments/assets/3c9628d6-5922-4422-8327-952e7ed0f673)

**Comment by vicanso** [comment]
删除server只能通过upgrade的方式启动新的实例，hot reload并不会修改server的相关参数，关联的location除外。upgrade暂时只能在linux（非docker)上运行，需要指定`-u -a`启动参数

**Comment by qiuyuyin** [comment]
是的，在linux环境运行的，-u -a 都启动了

**Comment by vicanso** [comment]
确认过程序是有upgrade重启成功了不？

**Comment by qiuyuyin** [comment]
是的，进程号都更换了

**Comment by vicanso** [comment]
4010是新加的端口，4000是旧的端口，是这样不？

**Comment by qiuyuyin** [comment]
嗯嗯

**Comment by vicanso** [comment]
我确认过了，的确存在这个问题，因为pingora使用upgrade时，会使用`fds.send_to_sock`将原有实例监听的连接转至新实例，因此导致原有实例的端口还是会被监听了。

暂时建议如果修改监听地址，则关闭程序再重启，后续我研究一下有否更好的方法。

**Comment by vicanso** [comment]
暂时无法解决此问题，对于监听端口有变化，如由4000端口修改为4001，只能通过关闭再开启程序解决。
