### ISSUE TITLE
期望Pingap/Pingora支持如下能力

### ISSUE THREAD

**Issue by zhangqiang-01** [vicanso/pingap#60]
我在从事CDN、动态加速接入相关工作，我在调研了Pingora之后发现如下能力不是特别理想。

1. 期望针对不同的域名设置不同的 SSL Cipher、SSL Protocols。
2. 期望支持SSL Session Ticket/ Session Cache。
3. 期望支持SSL OCSP 功能。

请问这些功能在Pingap上有计划落实吗？

**Comment by vicanso** [comment]
Pingap的基础能力都依赖于pingora，只是将各模块整合提供更便捷的配置方式而已。pingora支持ssl session ticket，其它的未找到具体实现
