### ISSUE TITLE
plugins per server

### ISSUE THREAD

**Issue by adammakowskidev** [vicanso/pingap#65]
Hi
I have a small problem.
I have several servers because I am building a small CDN, I use distrubuted posix filesystem storage.
So each server has the same configuration files and they are synchronised on each server.

I would like to identify the servers in some way, e.g. using the response_headers plugin by adding e.g:
x-proxy-node: germany-frankfurt on a server in Germany
x-proxy-node: poland-wroclaw on a server in Poland
and etc

The problem is that I cannot set it up at the moment because every server will return the same header, is there any way of solving this at the moment? I use new separate config.

**Comment by vicanso** [comment]
```toml
set_headers = ["x-proxy-node:$hostname"]
```

Or you can get value from env using `$ENV_KEY`.
