### ISSUE TITLE
doubt！

### ISSUE THREAD

**Issue by fastkits** [vicanso/pingap#68]
请问：存储配置是怎么个用法？

是否考虑把 存储配置 增加 yaml语法 json 等校验， 替代 类似consul的key/value功能

**Comment by vicanso** [comment]
主要用于密钥或者一些通用参数，例如鉴权相关的插件共用的鉴权参数等，不过暂时还未完善使用场景

**Comment by fastkits** [comment]
是否考虑把 存储配置 增加 yaml语法 json 等校验， 替代 类似consul的key/value功能

这个功能考虑吗

**Comment by vicanso** [comment]
这只是用于配置中的变量使用。pingap本身也没考虑需要保存啥数据，你考虑的应用场景是？

**Comment by fastkits** [comment]
把 pingap 打造为   nginx+配置中心( 替代consul ) + gateway 之类的 等等等等

**Comment by fastkits** [comment]
其他服务  从 pingap 获取配置，比如  config.json  ， config.yaml

**Comment by vicanso** [comment]
后续版本可以考虑，但不在近期计划内了。
