### ISSUE TITLE
如何添加自定义的插件

### ISSUE THREAD

**Issue by tqq1994516** [vicanso/pingap#71]
现在好像没有办法直接添加插件，是否只能通过fork repo然后自定义插件

**Comment by tqq1994516** [comment]
自定义认证和鉴权的插件

**Comment by vicanso** [comment]
现在已实现了一些鉴权的插件，可以提供具体的鉴权方式或者哪个反向代理已有的示例，我参考看看是否支持。

**Comment by tqq1994516** [comment]
> 现在已实现了一些鉴权的插件，可以提供具体的鉴权方式或者哪个反向代理已有的示例，我参考看看是否支持。

需要的是不通用的，所以才要自定义的插件，看来目前没有办法实现呢
