### ISSUE TITLE
avif files not cached

### ISSUE THREAD

**Issue by adammakowskidev** [vicanso/pingap#76]
Hi
I noticed today that avif (images) files are not cached by pingap

**Comment by vicanso** [comment]
Have you set max_file_size? If not, the default is 1mb.

**Comment by adammakowskidev** [comment]
I have a 10mb setting for this site so this is not a problem, my avif files are around 25kb.

**Comment by vicanso** [comment]
Please show me the config of cache plugin, I tried it and it's ok for avif.
```bash
curl 'http://127.0.0.1:6119/download.avif' -v
*   Trying 127.0.0.1:6119...
* Connected to 127.0.0.1 (127.0.0.1) port 6119
> GET /download.avif HTTP/1.1
> Host: 127.0.0.1:6119
> User-Agent: curl/8.7.1
> Accept: */*
>
* Request completely sent off
< HTTP/1.1 200 OK
< Content-Type: image/avif
< etag: W/"1b29-676fd2b7"
< Transfer-Encoding: chunked
< Cache-Control: public, max-age=3600
< Date: Sat, 28 Dec 2024 10:33:43 GMT
< Connection: keep-alive
< Age: 7
< X-Cache-Status: hit
< X-Cache-Lookup: 0ms
```

**Comment by adammakowskidev** [comment]
Sorry, for some reason these images do not return the cache-control header and I have the ‘Check Cache-Control response header’ set so it is my fault.
